apiVersion: v1
kind: Service
metadata:
  name: dev-psql-hl-svc  # hl (headless)
  namespace: ns-postgresql
  labels:
    app: psql-hl-svc
spec:
  clusterIP: None # Convierte el Service en un Headless Service. Esto significa que no se le asigna un ClusterIP único y no realiza balanceo de carga. En su lugar, el servidor DNS de Kubernetes devuelve las direcciones IP de los Pods que coinciden con el selector, lo que es vital para que un StatefulSet asigne identidades de red estables a cada Pod (por ejemplo, dev-psql-01-0.dev-psql-01-hl.ns-postgresql.svc.cluster.local).
  selector:
    app: psql
    ver: dev-01
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP

--- 

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: ns-postgresql
  labels:
    app: psql
    ver: dev-01
spec:
  type: NodePort
  selector:
    app: psql
    ver: dev-01
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
      nodePort: 30101    # Expone este Service en el puerto 30101 de cada nodo del clúster. 